package team6point7.dota2challenge;

public class image_list {
    int[] imgArray;

    public image_list(){
        imgArray = new int[116];
        imgArray[0] = R.drawable.hero1;
        imgArray[1] = R.drawable.hero2;
        imgArray[2] = R.drawable.hero3;
        imgArray[3] = R.drawable.hero4;
        imgArray[4] = R.drawable.hero5;
        imgArray[5] = R.drawable.hero6;
        imgArray[6] = R.drawable.hero7;
        imgArray[7] = R.drawable.hero8;
        imgArray[8] = R.drawable.hero9;
        imgArray[9] = R.drawable.hero10;
        imgArray[10] = R.drawable.hero11;
        imgArray[11] = R.drawable.hero12;
        imgArray[12] = R.drawable.hero13;
        imgArray[13] = R.drawable.hero14;
        imgArray[14] = R.drawable.hero15;
        imgArray[15] = R.drawable.hero16;
        imgArray[16] = R.drawable.hero17;
        imgArray[17] = R.drawable.hero18;
        imgArray[18] = R.drawable.hero19;
        imgArray[19] = R.drawable.hero20;
        imgArray[20] = R.drawable.hero21;
        imgArray[21] = R.drawable.hero22;
        imgArray[22] = R.drawable.hero23;
        imgArray[23] = R.drawable.hero24;
        imgArray[24] = R.drawable.hero25;
        imgArray[25] = R.drawable.hero26;
        imgArray[26] = R.drawable.hero27;
        imgArray[27] = R.drawable.hero28;
        imgArray[28] = R.drawable.hero29;
        imgArray[29] = R.drawable.hero30;
        imgArray[30] = R.drawable.hero31;
        imgArray[31] = R.drawable.hero32;
        imgArray[32] = R.drawable.hero33;
        imgArray[33] = R.drawable.hero34;
        imgArray[34] = R.drawable.hero35;
        imgArray[35] = R.drawable.hero36;
        imgArray[36] = R.drawable.hero37;
        imgArray[37] = R.drawable.hero38;
        imgArray[38] = R.drawable.hero39;
        imgArray[39] = R.drawable.hero40;
        imgArray[40] = R.drawable.hero41;
        imgArray[41] = R.drawable.hero42;
        imgArray[42] = R.drawable.hero43;
        imgArray[43] = R.drawable.hero44;
        imgArray[44] = R.drawable.hero45;
        imgArray[45] = R.drawable.hero46;
        imgArray[46] = R.drawable.hero47;
        imgArray[47] = R.drawable.hero48;
        imgArray[48] = R.drawable.hero49;
        imgArray[49] = R.drawable.hero50;
        imgArray[50] = R.drawable.hero51;
        imgArray[51] = R.drawable.hero52;
        imgArray[52] = R.drawable.hero53;
        imgArray[53] = R.drawable.hero54;
        imgArray[54] = R.drawable.hero55;
        imgArray[55] = R.drawable.hero56;
        imgArray[56] = R.drawable.hero57;
        imgArray[57] = R.drawable.hero58;
        imgArray[58] = R.drawable.hero59;
        imgArray[59] = R.drawable.hero60;
        imgArray[60] = R.drawable.hero61;
        imgArray[61] = R.drawable.hero62;
        imgArray[62] = R.drawable.hero63;
        imgArray[63] = R.drawable.hero64;
        imgArray[64] = R.drawable.hero65;
        imgArray[65] = R.drawable.hero66;
        imgArray[66] = R.drawable.hero67;
        imgArray[67] = R.drawable.hero68;
        imgArray[68] = R.drawable.hero69;
        imgArray[69] = R.drawable.hero70;
        imgArray[70] = R.drawable.hero71;
        imgArray[71] = R.drawable.hero72;
        imgArray[72] = R.drawable.hero73;
        imgArray[73] = R.drawable.hero74;
        imgArray[74] = R.drawable.hero75;
        imgArray[75] = R.drawable.hero76;
        imgArray[76] = R.drawable.hero77;
        imgArray[77] = R.drawable.hero78;
        imgArray[78] = R.drawable.hero79;
        imgArray[79] = R.drawable.hero80;
        imgArray[80] = R.drawable.hero81;
        imgArray[81] = R.drawable.hero82;
        imgArray[82] = R.drawable.hero83;
        imgArray[83] = R.drawable.hero84;
        imgArray[84] = R.drawable.hero85;
        imgArray[85] = R.drawable.hero86;
        imgArray[86] = R.drawable.hero87;
        imgArray[87] = R.drawable.hero88;
        imgArray[88] = R.drawable.hero89;
        imgArray[89] = R.drawable.hero90;
        imgArray[90] = R.drawable.hero91;
        imgArray[91] = R.drawable.hero92;
        imgArray[92] = R.drawable.hero93;
        imgArray[93] = R.drawable.hero94;
        imgArray[94] = R.drawable.hero95;
        imgArray[95] = R.drawable.hero96;
        imgArray[96] = R.drawable.hero97;
        imgArray[97] = R.drawable.hero98;
        imgArray[98] = R.drawable.hero99;
        imgArray[99] = R.drawable.hero100;
        imgArray[100] = R.drawable.hero101;
        imgArray[101] = R.drawable.hero102;
        imgArray[102] = R.drawable.hero103;
        imgArray[103] = R.drawable.hero104;
        imgArray[104] = R.drawable.hero105;
        imgArray[105] = R.drawable.hero106;
        imgArray[106] = R.drawable.hero107;
        imgArray[107] = R.drawable.hero108;
        imgArray[108] = R.drawable.hero109;
        imgArray[109] = R.drawable.hero110;
        imgArray[110] = R.drawable.hero111;
        imgArray[111] = R.drawable.hero112;
        imgArray[112] = R.drawable.hero113;
        imgArray[113] = R.drawable.hero114;
        imgArray[114] = R.drawable.hero115;
        imgArray[115] = R.drawable.hero116;
    }

    public int getList(int x){
        return imgArray[x];
    }

}
